package day04;

import java.io.IOException;

public class ExceptionTest {
	public static void main(String[] args) {
		int a = 0;
		double b;
		try {
			b = 100/a;
			System.out.println("Some more codes in try block");
		}
		catch(ArithmeticException e) {
			System.out.println("Exception occurred : "+e);
		}
		catch(IOException e2) {
			System.out.println("One more catch block");
		}
		finally {
			System.out.println("Some more codes in finally block");
		}
	}
}
